/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author josera
 */
public class jVivienda extends javax.swing.JFrame {

    /**
     * Creates new form jCasa
     */
    public jVivienda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jTextFieldHabitaciones = new javax.swing.JTextField();
        jTextFieldBannios = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jButtonGuardar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jTextfieldIDPropietario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxUrbanizacion = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxIdEdificio = new javax.swing.JComboBox<>();
        lblIdCalle = new javax.swing.JLabel();
        jComboBoxIdCalle = new javax.swing.JComboBox<>();
        lblIdEdificio = new javax.swing.JLabel();
        jComboBoxPiso = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jComboBoxBuscarCodigo = new javax.swing.JComboBox<>();
        lblBuscar = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vivienda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 102, 153))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(716, 312));
        jPanel1.setMinimumSize(new java.awt.Dimension(716, 312));
        jPanel1.setPreferredSize(new java.awt.Dimension(716, 312));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nro. de Habitaciones:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(360, 180, 150, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Código");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(490, 40, 50, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nro de Baños:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 230, 100, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Nro. de Teléfono:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(380, 230, 130, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Tipo de Vivienda");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 90, 113, 17);

        jTextFieldCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldCodigo.setEnabled(false);
        jPanel1.add(jTextFieldCodigo);
        jTextFieldCodigo.setBounds(550, 40, 160, 25);

        jTextFieldHabitaciones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jTextFieldHabitaciones);
        jTextFieldHabitaciones.setBounds(520, 180, 80, 25);

        jTextFieldBannios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jTextFieldBannios);
        jTextFieldBannios.setBounds(180, 230, 120, 25);

        jTextFieldTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jTextFieldTelefono);
        jTextFieldTelefono.setBounds(510, 230, 140, 25);

        jComboBoxTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxTipo.setMaximumRowCount(10);
        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "CASA", "APTO" }));
        jComboBoxTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTipoItemStateChanged(evt);
            }
        });
        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxTipo);
        jComboBoxTipo.setBounds(30, 110, 110, 20);

        jButtonGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Guardar-48.png"))); // NOI18N
        jButtonGuardar.setText("Guardar");
        jPanel1.add(jButtonGuardar);
        jButtonGuardar.setBounds(10, 380, 120, 40);

        jButtonEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Eliminar-48.png"))); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jPanel1.add(jButtonEliminar);
        jButtonEliminar.setBounds(180, 380, 112, 40);

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Escoba-48.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jPanel1.add(jButtonCancelar);
        jButtonCancelar.setBounds(320, 380, 117, 40);

        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Volver-48.png"))); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jButtonSalirStateChanged(evt);
            }
        });
        jPanel1.add(jButtonSalir);
        jButtonSalir.setBounds(470, 380, 87, 40);

        jTextfieldIDPropietario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextfieldIDPropietario.setEnabled(false);
        jTextfieldIDPropietario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextfieldIDPropietarioKeyTyped(evt);
            }
        });
        jPanel1.add(jTextfieldIDPropietario);
        jTextfieldIDPropietario.setBounds(180, 180, 120, 25);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Cedula del Propietario:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 180, 160, 20);

        jComboBoxUrbanizacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxUrbanizacion.setMaximumRowCount(10);
        jComboBoxUrbanizacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        jComboBoxUrbanizacion.setEnabled(false);
        jComboBoxUrbanizacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxUrbanizacionItemStateChanged(evt);
            }
        });
        jComboBoxUrbanizacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxUrbanizacionMouseClicked(evt);
            }
        });
        jComboBoxUrbanizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUrbanizacionActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxUrbanizacion);
        jComboBoxUrbanizacion.setBounds(160, 110, 110, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Urbanización");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(170, 90, 90, 17);

        jComboBoxIdEdificio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxIdEdificio.setMaximumRowCount(10);
        jComboBoxIdEdificio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        jComboBoxIdEdificio.setEnabled(false);
        jComboBoxIdEdificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIdEdificioActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxIdEdificio);
        jComboBoxIdEdificio.setBounds(300, 110, 120, 20);

        lblIdCalle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIdCalle.setText("Id de la Calle");
        jPanel1.add(lblIdCalle);
        lblIdCalle.setBounds(460, 90, 100, 17);

        jComboBoxIdCalle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxIdCalle.setMaximumRowCount(10);
        jComboBoxIdCalle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        jComboBoxIdCalle.setEnabled(false);
        jPanel1.add(jComboBoxIdCalle);
        jComboBoxIdCalle.setBounds(440, 110, 120, 20);

        lblIdEdificio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIdEdificio.setText("Id del Edificio");
        jPanel1.add(lblIdEdificio);
        lblIdEdificio.setBounds(310, 90, 100, 17);

        jComboBoxPiso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxPiso.setMaximumRowCount(10);
        jComboBoxPiso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        jComboBoxPiso.setEnabled(false);
        jComboBoxPiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPisoActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxPiso);
        jComboBoxPiso.setBounds(580, 110, 120, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Blue Condos Logo Blanco.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(600, 280, 390, 150);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("  *");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(700, 110, 20, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("  *");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(600, 180, 20, 15);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("  *");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(300, 180, 20, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("  *");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(300, 230, 30, 15);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Los Campos con * son Obligatorios");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(210, 440, 220, 15);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("  *");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(140, 110, 20, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("  *");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(270, 110, 20, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("  *");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(560, 110, 20, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("  *");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(420, 110, 20, 30);

        jComboBoxBuscarCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxBuscarCodigo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        jPanel1.add(jComboBoxBuscarCodigo);
        jComboBoxBuscarCodigo.setBounds(270, 40, 180, 27);

        lblBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBuscar.setText("     Buscar Vivienda: ");
        jPanel1.add(lblBuscar);
        lblBuscar.setBounds(120, 40, 140, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("               Piso");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(580, 90, 120, 17);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setjTextFieldCodigo(JTextField jTextFieldCodigo) {
        this.jTextFieldCodigo = jTextFieldCodigo;
    }
    
    public JComboBox<String> getjComboBoxCalle()
    { 
        return jComboBoxIdCalle;
    }
    public JComboBox<String> getjComboBoxEdificio()
    { 
        return jComboBoxIdEdificio;
    }
    public JComboBox<String> getjComboBoxPiso()
    { 
        return jComboBoxPiso;
    }
    public JComboBox<String> getjComboBoxUrbanizacion() {
        return jComboBoxUrbanizacion;
    }

    public JTextField getjTextfieldIDPropietario() {
        return jTextfieldIDPropietario;
    }
    public  JComboBox getjComboboxBuscarCodigo()
    {
        return jComboBoxBuscarCodigo;
    }

    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed

       
    }//GEN-LAST:event_jComboBoxTipoActionPerformed

    private void jComboBoxUrbanizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUrbanizacionActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jComboBoxUrbanizacionActionPerformed

    private void jTextfieldIDPropietarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextfieldIDPropietarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextfieldIDPropietarioKeyTyped

    private void jComboBoxIdEdificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIdEdificioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxIdEdificioActionPerformed

    private void jButtonSalirStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jButtonSalirStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirStateChanged

    private void jComboBoxUrbanizacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxUrbanizacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUrbanizacionMouseClicked

    private void jComboBoxUrbanizacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxUrbanizacionItemStateChanged
     
    }//GEN-LAST:event_jComboBoxUrbanizacionItemStateChanged

    private void jComboBoxTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTipoItemStateChanged
    
    }//GEN-LAST:event_jComboBoxTipoItemStateChanged

    private void jComboBoxPisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPisoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jVivienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jVivienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jVivienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jVivienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jVivienda().setVisible(true);
            }
        });
    }

    public JTextField getjTextFieldCodigo() {
        return jTextFieldCodigo;
    }
    
    public JTextField getjTextFieldHabitaciones() {
        return jTextFieldHabitaciones;
    }
    
    public JTextField getjTextFieldBannios() {
        return jTextFieldBannios;
    }
    
    public JTextField getjTextFieldTelefono() {
        return jTextFieldTelefono;
    }
    
    
    public JComboBox getjComboBoxTipo() {
        return jComboBoxTipo;
    }
    
    public JButton getjButtonGuardar() {
        return jButtonGuardar;
    }
    
    public JButton getjButtonEliminar() {
        return jButtonEliminar;
    }
    
    public JButton getjButtonCancelar() {
        return jButtonCancelar;
    }
    
    public JButton getjButtonSalir() {
        return jButtonSalir;
    }
    
    public void agregarListener(ActionListener action) {
        this.jButtonGuardar.addActionListener(action);
        this.jButtonEliminar.addActionListener(action);
        this.jButtonCancelar.addActionListener(action);
        this.jButtonSalir.addActionListener(action);
        this.jComboBoxTipo.addActionListener(action);
        this.jComboBoxUrbanizacion.addActionListener(action);
        this.jComboBoxIdEdificio.addActionListener(action);
        this.jComboBoxIdCalle.addActionListener(action);
        this.jComboBoxBuscarCodigo.addActionListener(action);
    }
    
    public void agregarItemListener(ItemListener il)
    {
      this.jComboBoxTipo.addItemListener(il);
      this.jComboBoxUrbanizacion.addItemListener(il);
      this.jComboBoxIdEdificio.addItemListener(il);
      this.jComboBoxIdCalle.addItemListener(il);
      this.jComboBoxBuscarCodigo.addItemListener(il);
      
    }
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<String> jComboBoxBuscarCodigo;
    private javax.swing.JComboBox<String> jComboBoxIdCalle;
    private javax.swing.JComboBox<String> jComboBoxIdEdificio;
    private javax.swing.JComboBox<String> jComboBoxPiso;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JComboBox<String> jComboBoxUrbanizacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldBannios;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldHabitaciones;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JTextField jTextfieldIDPropietario;
    private java.awt.Label label1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblIdCalle;
    private javax.swing.JLabel lblIdEdificio;
    // End of variables declaration//GEN-END:variables

    public void setjComboBoxTipo(JComboBox<String> jComboBoxTipo) {
        this.jComboBoxTipo = jComboBoxTipo;
    }
     public void setjComboBoxPiso(JComboBox<String> jComboBoxPiso) {
        this.jComboBoxPiso = jComboBoxPiso;
    }
    public void setjComboBoxUrbanizacion(JComboBox<String> jComboBoxUrbanizacion) {
        this.jComboBoxUrbanizacion = jComboBoxUrbanizacion;
    }

}
